### ISSUE TITLE
how to Dynamic open a url pdf link by js code

### ISSUE THREAD

**Issue by zj2050** [foxitsoftware/WebPDF.js#4]
hi,

would you pls give a doc for how to Dynamic open a url pdf link by javascript code

thanks

**Comment by Nancy036** [comment]
Hi, 
you can open a URL pdf as below:
  `PDFViewerApplication.open(fileUrl)`
replace the document URL with "fileUrl'. Please note that the document URL should be cross-domain access supported  by JavaScirpt.

Nancy
