### ISSUE TITLE
How can i get a license key

### ISSUE THREAD

**Issue by gfaz** [foxitsoftware/WebPDF.js#5]
Hi,
    I want a license key to read pdf files in firefox or chrome. How can i get it?
    I had send a email to webpdfdemo@foxitsoftware.com, but I haven't received a reply.
    What should I do?
    Thank you.

**Comment by jyothipotluri** [comment]
gfaz,

Did anyone get back to you regarding the license? I am on the same boat right now... no response from them after sending several emails.

-jyothi

**Comment by rowanhanna** [comment]
Hi gfaz and jyothi, you should have received the license keys now, let me know if that isn't the case and I'll help you. Apologies for the glitch that resulted in them not getting sent out.

**Comment by gfaz** [comment]
Thank you. I had got the license key. I will use it if it is valid. 
Thanks again.

**Comment by dalbir** [comment]
@rowanhanna I have also not received the License Key. Please help me asap. MY company email id is dsingh11@bechtel.com

**Comment by yerayrm** [comment]
@rowanhanna Can you provide me the license key? I sent an email and I need the license to test this library asap.

Best regards
