### ISSUE TITLE
License, IE11 issues

### ISSUE THREAD

**Issue by jyothipotluri** [foxitsoftware/WebPDF.js#6]
The trial license provided is not working. Can you please provide the latest license key. I have tried emailing the address provided but, has not received any response.

**Comment by rowanhanna** [comment]
You should have received the license key now, please re-open this issue if that is not the case.

**Comment by jyothipotluri** [comment]
Rowan,

Got the license. Thank you. But, I am having trouble using the Javascript library in IE11. Are there any known issues with IE11?
Looks like IE11 doesn’t have all the required fonts for some of the PDF that I need to display and it cannot contact the external website provided for fonts. Is there any other way to get the fonts?

Thank you.
Jyothi
